import { createContext, useContext, useMemo, useState, type ReactNode } from 'react';
import toast from 'react-hot-toast';
import type { Asset, AssetRequest, Assignment, AssignmentRequest, MaintenanceRecord, MaintenanceRequestDto, ManagedUser, Permission, StockItem, StockItemRequest, StockTransaction, UpdateUserRequest, CreateUserRequest, WorkspaceData } from '../api/types';
import { createSeedWorkspace } from '../data/seed';
import { can } from '../utils/permissions';
import { useAuth } from './AuthContext';

const KEY='nexora_assetops_workspace_v5';
function load():WorkspaceData{ try{const raw=localStorage.getItem(KEY); if(raw){const parsed=JSON.parse(raw) as WorkspaceData; if(parsed?.metadata?.version===5)return parsed;}}catch{} const seeded=createSeedWorkspace(); localStorage.setItem(KEY,JSON.stringify(seeded)); return seeded; }
function nextId<T extends {id:number}>(items:T[]){return Math.max(0,...items.map(x=>x.id))+1;}

type Ctx={
 data:WorkspaceData; resetWorkspace:()=>void;
 addAsset:(p:AssetRequest)=>Asset; updateAsset:(id:number,p:AssetRequest)=>Asset; deleteAsset:(id:number)=>void;
 addStock:(p:StockItemRequest)=>StockItem; updateStock:(id:number,p:StockItemRequest)=>StockItem; deleteStock:(id:number)=>void; moveStock:(id:number,type:'IN'|'OUT',quantity:number,reason:string)=>void;
 assignAsset:(p:AssignmentRequest)=>Assignment; returnAsset:(id:number,notes?:string)=>void;
 addMaintenance:(p:MaintenanceRequestDto)=>MaintenanceRecord; updateMaintenance:(id:number,p:MaintenanceRequestDto)=>MaintenanceRecord; deleteMaintenance:(id:number)=>void; setMaintenanceStatus:(id:number,status:MaintenanceRecord['status'])=>void;
 addUser:(p:CreateUserRequest)=>ManagedUser; updateUser:(id:number,p:UpdateUserRequest)=>ManagedUser; deleteUser:(id:number)=>void;
 has:(permission:Permission)=>boolean;
};
const WorkspaceContext=createContext<Ctx|undefined>(undefined);

export function WorkspaceProvider({children}:{children:ReactNode}){
 const {user}=useAuth();
 const [data,setData]=useState<WorkspaceData>(()=>load());
 const persist=(producer:(prev:WorkspaceData)=>WorkspaceData)=>setData(prev=>{const next=producer(prev); localStorage.setItem(KEY,JSON.stringify(next)); return next;});
 const requirePermission=(p:Permission)=>{ if(!can(user?.role,p)){toast.error('Your role does not have permission for this action.'); throw new Error('Permission denied');}};
 const addActivity=(d:WorkspaceData,description:string,entityType:string,entityId:number,action='UPDATE'):WorkspaceData=>({ ...d, activities:[{id:nextId(d.activities),action,entityType,entityId,description,username:user?.username||'system',createdAt:new Date().toISOString()},...d.activities].slice(0,120)});

 const value=useMemo<Ctx>(()=>({
  data,
  has:(p)=>can(user?.role,p),
  resetWorkspace:()=>{requirePermission('users.manage'); const seeded=createSeedWorkspace(); localStorage.setItem(KEY,JSON.stringify(seeded)); setData(seeded); toast.success('Workspace restored to the professional seeded dataset.');},
  addAsset:(p)=>{requirePermission('assets.write'); let created!:Asset; persist(d=>{const id=nextId(d.assets); created={id,assetCode:`NX-${p.category.slice(0,3)}-${String(1000+id).padStart(4,'0')}`,...p,status:p.status||'AVAILABLE',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),qrCodeData:`NEXORA:ASSET:${id}`}; return addActivity({...d,assets:[created,...d.assets]},`Created asset ${created.assetCode} · ${created.name}`,'Asset',id,'CREATE');}); return created;},
  updateAsset:(id,p)=>{requirePermission('assets.write'); let updated!:Asset; persist(d=>{const current=d.assets.find(x=>x.id===id); if(!current)throw new Error('Asset not found'); updated={...current,...p,status:p.status||current.status,updatedAt:new Date().toISOString()}; return addActivity({...d,assets:d.assets.map(x=>x.id===id?updated:x)},`Updated asset ${updated.assetCode} · ${updated.name}`,'Asset',id);}); return updated;},
  deleteAsset:(id)=>{requirePermission('assets.write'); persist(d=>{const a=d.assets.find(x=>x.id===id); if(!a)throw new Error('Asset not found'); if(d.assignments.some(x=>x.assetId===id&&x.status==='ACTIVE'))throw new Error('Return the active assignment before deleting this asset.'); return addActivity({...d,assets:d.assets.filter(x=>x.id!==id),maintenance:d.maintenance.filter(x=>x.assetId!==id)},`Removed asset ${a.assetCode} from the active register`,'Asset',id,'DELETE');});},
  addStock:(p)=>{requirePermission('stock.write'); let created!:StockItem; persist(d=>{const id=nextId(d.stock); created={id,...p,lowStock:p.quantity<=p.minimumStock,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}; return addActivity({...d,stock:[created,...d.stock]},`Registered inventory item ${created.sku} · ${created.itemName}`,'Stock',id,'CREATE');}); return created;},
  updateStock:(id,p)=>{requirePermission('stock.write'); let updated!:StockItem; persist(d=>{const c=d.stock.find(x=>x.id===id); if(!c)throw new Error('Stock item not found'); updated={...c,...p,lowStock:p.quantity<=p.minimumStock,updatedAt:new Date().toISOString()}; return addActivity({...d,stock:d.stock.map(x=>x.id===id?updated:x)},`Updated inventory item ${updated.sku}`,'Stock',id);}); return updated;},
  deleteStock:(id)=>{requirePermission('stock.write'); persist(d=>{const x=d.stock.find(s=>s.id===id); if(!x)throw new Error('Stock item not found'); return addActivity({...d,stock:d.stock.filter(s=>s.id!==id),stockTransactions:d.stockTransactions.filter(t=>t.stockItemId!==id)},`Removed inventory item ${x.sku}`,'Stock',id,'DELETE');});},
  moveStock:(id,type,quantity,reason)=>{requirePermission('stock.write'); if(quantity<=0)throw new Error('Quantity must be greater than zero'); persist(d=>{const item=d.stock.find(x=>x.id===id); if(!item)throw new Error('Stock item not found'); if(type==='OUT'&&quantity>item.quantity)throw new Error('Insufficient quantity for this stock issue.'); const q=item.quantity+(type==='IN'?quantity:-quantity); const updated={...item,quantity:q,lowStock:q<=item.minimumStock,updatedAt:new Date().toISOString()}; const tx:StockTransaction={id:nextId(d.stockTransactions),stockItemId:id,itemName:item.itemName,sku:item.sku,type,quantity,reason,performedBy:user?.username||'system',createdAt:new Date().toISOString()}; return addActivity({...d,stock:d.stock.map(x=>x.id===id?updated:x),stockTransactions:[tx,...d.stockTransactions]},`${type==='IN'?'Received':'Issued'} ${quantity} × ${item.itemName}`,'Stock',id,type==='IN'?'STOCK_IN':'STOCK_OUT');});},
  assignAsset:(p)=>{requirePermission('assignments.write'); let created!:Assignment; persist(d=>{const a=d.assets.find(x=>x.id===p.assetId); if(!a)throw new Error('Asset not found'); if(a.status!=='AVAILABLE')throw new Error('Only available assets can be assigned.'); const id=nextId(d.assignments); created={id,assetId:a.id,assetCode:a.assetCode,assetName:a.name,employeeName:p.employeeName,employeeId:p.employeeId,department:p.department,assignmentDate:p.assignmentDate||new Date().toISOString().slice(0,10),expectedReturnDate:p.expectedReturnDate,status:'ACTIVE',notes:p.notes,assignedBy:user?.username,createdAt:new Date().toISOString()}; return addActivity({...d,assignments:[created,...d.assignments],assets:d.assets.map(x=>x.id===a.id?{...x,status:'ASSIGNED',updatedAt:new Date().toISOString()}:x)},`Assigned ${a.assetCode} to ${p.employeeName}`,'Assignment',id,'ASSIGN');}); return created;},
  returnAsset:(id,notes)=>{requirePermission('assignments.write'); persist(d=>{const a=d.assignments.find(x=>x.id===id); if(!a)throw new Error('Assignment not found'); if(a.status==='RETURNED')throw new Error('Assignment already returned'); const returned={...a,status:'RETURNED' as const,returnDate:new Date().toISOString().slice(0,10),notes:notes||a.notes}; return addActivity({...d,assignments:d.assignments.map(x=>x.id===id?returned:x),assets:d.assets.map(x=>x.id===a.assetId?{...x,status:'AVAILABLE',updatedAt:new Date().toISOString()}:x)},`Returned ${a.assetCode} from ${a.employeeName}`,'Assignment',id,'RETURN');});},
  addMaintenance:(p)=>{requirePermission('maintenance.write'); let created!:MaintenanceRecord; persist(d=>{const a=d.assets.find(x=>x.id===p.assetId); if(!a)throw new Error('Asset not found'); const id=nextId(d.maintenance); created={id,assetId:a.id,assetCode:a.assetCode,assetName:a.name,title:p.title,description:p.description,scheduleDate:p.scheduleDate,technician:p.technician,vendor:p.vendor,cost:p.cost,status:p.status||'SCHEDULED',createdBy:user?.username,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}; const assets=created.status==='IN_PROGRESS'?d.assets.map(x=>x.id===a.id?{...x,status:'UNDER_MAINTENANCE' as const}:x):d.assets; return addActivity({...d,maintenance:[created,...d.maintenance],assets},`Created maintenance ticket for ${a.assetCode}`,'Maintenance',id,'CREATE');}); return created;},
  updateMaintenance:(id,p)=>{requirePermission('maintenance.write'); let updated!:MaintenanceRecord; persist(d=>{const c=d.maintenance.find(x=>x.id===id); if(!c)throw new Error('Maintenance record not found'); const a=d.assets.find(x=>x.id===p.assetId)||d.assets.find(x=>x.id===c.assetId)!; updated={...c,...p,assetId:a.id,assetCode:a.assetCode,assetName:a.name,status:p.status||c.status,updatedAt:new Date().toISOString()}; return addActivity({...d,maintenance:d.maintenance.map(x=>x.id===id?updated:x)},`Updated maintenance ticket #${id} for ${a.assetCode}`,'Maintenance',id);}); return updated;},
  deleteMaintenance:(id)=>{requirePermission('maintenance.write'); persist(d=>addActivity({...d,maintenance:d.maintenance.filter(x=>x.id!==id)},`Removed maintenance ticket #${id}`,'Maintenance',id,'DELETE'));},
  setMaintenanceStatus:(id,status)=>{requirePermission('maintenance.write'); persist(d=>{const m=d.maintenance.find(x=>x.id===id); if(!m)throw new Error('Maintenance record not found'); const updated={...m,status,completedDate:status==='COMPLETED'?new Date().toISOString().slice(0,10):m.completedDate,updatedAt:new Date().toISOString()}; const assets=d.assets.map(a=>a.id!==m.assetId?a:{...a,status:status==='IN_PROGRESS'?'UNDER_MAINTENANCE':status==='COMPLETED'&&a.status==='UNDER_MAINTENANCE'?'AVAILABLE':a.status} as Asset); return addActivity({...d,maintenance:d.maintenance.map(x=>x.id===id?updated:x),assets},`Changed maintenance #${id} to ${status.replace(/_/g,' ')}`,'Maintenance',id,'STATUS');});},
  addUser:(p)=>{requirePermission('users.manage'); let created!:ManagedUser; persist(d=>{if(d.users.some(x=>x.username.toLowerCase()===p.username.toLowerCase()))throw new Error('Username already exists'); const id=nextId(d.users); created={id,...p,active:true,createdAt:new Date().toISOString()}; return addActivity({...d,users:[created,...d.users]},`Created user @${created.username} with role ${created.role}`,'User',id,'CREATE');}); return created;},
  updateUser:(id,p)=>{requirePermission('users.manage'); let updated!:ManagedUser; persist(d=>{const c=d.users.find(x=>x.id===id); if(!c)throw new Error('User not found'); updated={...c,...p,password:p.password?.trim()?p.password:c.password}; return addActivity({...d,users:d.users.map(x=>x.id===id?updated:x)},`Updated access profile for @${updated.username}`,'User',id);}); return updated;},
  deleteUser:(id)=>{requirePermission('users.manage'); if(user?.id===id)throw new Error('You cannot delete the account you are currently using.'); persist(d=>{const x=d.users.find(u=>u.id===id); if(!x)throw new Error('User not found'); return addActivity({...d,users:d.users.filter(u=>u.id!==id)},`Removed workspace user @${x.username}`,'User',id,'DELETE');});},
 }),[data,user]);
 return <WorkspaceContext.Provider value={value}>{children}</WorkspaceContext.Provider>;
}
export function useWorkspace(){const c=useContext(WorkspaceContext); if(!c)throw new Error('useWorkspace must be used inside WorkspaceProvider'); return c;}

