import { useMemo, useState } from 'react';
import { Eye, HardDrive, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import toast from 'react-hot-toast';
import { useWorkspace } from '../context/WorkspaceContext';
import type { Asset, AssetCategory, AssetRequest, AssetStatus } from '../api/types';
import Modal from '../components/ui/Modal';
import Button from '../components/ui/Button';
import { ASSET_CATEGORIES, ASSET_CATEGORY_LABELS, ASSET_STATUSES, ASSET_STATUS_LABELS } from '../utils/labels';
import { formatCurrency, formatDate } from '../utils/format';
const empty:AssetRequest={name:'',serialNumber:'',category:'LAPTOPS',purchaseDate:new Date().toISOString().slice(0,10),purchaseCost:1200,warrantyExpiry:'',location:'HQ · Floor 2',status:'AVAILABLE',vendor:'TechSource Africa',department:'IT',condition:'EXCELLENT',notes:''};
export default function AssetsPage(){const {data,addAsset,updateAsset,deleteAsset,has}=useWorkspace();const [search,setSearch]=useState('');const [status,setStatus]=useState<AssetStatus|''>('');const [category,setCategory]=useState<AssetCategory|''>('');const [open,setOpen]=useState(false);const [detail,setDetail]=useState<Asset|null>(null);const [editing,setEditing]=useState<Asset|null>(null);const [form,setForm]=useState<AssetRequest>(empty);const [page,setPage]=useState(0);const size=12;const canWrite=has('assets.write');
 const filtered=useMemo(()=>data.assets.filter(a=>(!search||`${a.assetCode} ${a.name} ${a.serialNumber} ${a.location} ${a.department}`.toLowerCase().includes(search.toLowerCase()))&&(!status||a.status===status)&&(!category||a.category===category)),[data.assets,search,status,category]);const pages=Math.max(1,Math.ceil(filtered.length/size));const rows=filtered.slice(page*size,page*size+size);
 const launch=(a?:Asset)=>{if(a){setEditing(a);setForm({name:a.name,serialNumber:a.serialNumber,category:a.category,purchaseDate:a.purchaseDate,purchaseCost:a.purchaseCost,warrantyExpiry:a.warrantyExpiry,location:a.location,status:a.status,vendor:a.vendor,department:a.department,condition:a.condition,notes:a.notes})}else{setEditing(null);setForm(empty)}setOpen(true)};
 const save=(e:React.FormEvent)=>{e.preventDefault();try{if(!form.name.trim())throw new Error('Asset name is required');editing?updateAsset(editing.id,form):addAsset(form);toast.success(editing?'Asset updated successfully':'Asset registered successfully');setOpen(false)}catch(err:any){toast.error(err.message)}};
 const remove=(a:Asset)=>{if(!confirm(`Remove ${a.assetCode} · ${a.name}?`))return;try{deleteAsset(a.id);toast.success('Asset removed')}catch(err:any){toast.error(err.message)}};
 return <div className="space-y-5"><div className="page-head"><div><p className="eyebrow">Lifecycle management</p><h1 className="page-title">Asset Registry</h1><p className="page-subtitle">Track identity, custody, location, value, warranty and condition across the enterprise.</p></div>{canWrite&&<Button onClick={()=>launch()} icon={<Plus className="h-4 w-4"/>}>Register asset</Button>}</div>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="mini-stat"><span>Total register</span><b>{data.assets.length}</b></div><div className="mini-stat"><span>Available</span><b>{data.assets.filter(a=>a.status==='AVAILABLE').length}</b></div><div className="mini-stat"><span>Assigned</span><b>{data.assets.filter(a=>a.status==='ASSIGNED').length}</b></div><div className="mini-stat"><span>Portfolio value</span><b>{formatCurrency(data.assets.reduce((s,a)=>s+(a.purchaseCost||0),0))}</b></div></div>
 <div className="panel p-4"><div className="grid gap-3 lg:grid-cols-[1fr_220px_220px]"><div className="relative"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input className="input pl-10" value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}} placeholder="Search code, name, serial, location or department…"/></div><select className="input" value={status} onChange={e=>{setStatus(e.target.value as any);setPage(0)}}><option value="">All statuses</option>{ASSET_STATUSES.map(s=><option key={s} value={s}>{ASSET_STATUS_LABELS[s]}</option>)}</select><select className="input" value={category} onChange={e=>{setCategory(e.target.value as any);setPage(0)}}><option value="">All categories</option>{ASSET_CATEGORIES.map(c=><option key={c} value={c}>{ASSET_CATEGORY_LABELS[c]}</option>)}</select></div></div>
 <div className="panel overflow-hidden p-0"><div className="overflow-x-auto"><table className="pro-table"><thead><tr><th>Asset</th><th>Category</th><th>Department</th><th>Location</th><th>Condition</th><th>Status</th><th>Acquisition</th><th></th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td><div><p className="font-bold text-slate-900">{a.name}</p><p className="mt-0.5 font-mono text-[11px] text-blue-600">{a.assetCode} · {a.serialNumber}</p></div></td><td>{ASSET_CATEGORY_LABELS[a.category]}</td><td>{a.department||'—'}</td><td>{a.location||'—'}</td><td><span className="soft-badge">{a.condition||'GOOD'}</span></td><td><span className={`status-pill status-${a.status.toLowerCase()}`}>{ASSET_STATUS_LABELS[a.status]}</span></td><td><p className="font-semibold">{formatCurrency(a.purchaseCost)}</p><p className="text-[11px] text-slate-400">{formatDate(a.purchaseDate)}</p></td><td><div className="flex justify-end gap-1"><button className="icon-btn" onClick={()=>setDetail(a)}><Eye className="h-4 w-4"/></button>{canWrite&&<><button className="icon-btn" onClick={()=>launch(a)}><Pencil className="h-4 w-4"/></button><button className="icon-btn danger" onClick={()=>remove(a)}><Trash2 className="h-4 w-4"/></button></>}</div></td></tr>)}</tbody></table></div><div className="table-footer"><span>Showing {rows.length} of {filtered.length} matching assets</span><div className="flex gap-2"><button className="pager" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span className="pager-info">{page+1} / {pages}</span><button className="pager" disabled={page>=pages-1} onClick={()=>setPage(p=>p+1)}>Next</button></div></div></div>
 <Modal open={open} onClose={()=>setOpen(false)} title={editing?'Update asset record':'Register new asset'} size="xl"><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><Field label="Asset name"><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Serial number"><input className="input" value={form.serialNumber||''} onChange={e=>setForm({...form,serialNumber:e.target.value})}/></Field><Field label="Category"><select className="input" value={form.category} onChange={e=>setForm({...form,category:e.target.value as AssetCategory})}>{ASSET_CATEGORIES.map(c=><option key={c} value={c}>{ASSET_CATEGORY_LABELS[c]}</option>)}</select></Field><Field label="Status"><select className="input" value={form.status} onChange={e=>setForm({...form,status:e.target.value as AssetStatus})}>{ASSET_STATUSES.map(s=><option key={s} value={s}>{ASSET_STATUS_LABELS[s]}</option>)}</select></Field><Field label="Department"><input className="input" value={form.department||''} onChange={e=>setForm({...form,department:e.target.value})}/></Field><Field label="Location"><input className="input" value={form.location||''} onChange={e=>setForm({...form,location:e.target.value})}/></Field><Field label="Vendor"><input className="input" value={form.vendor||''} onChange={e=>setForm({...form,vendor:e.target.value})}/></Field><Field label="Condition"><select className="input" value={form.condition||'EXCELLENT'} onChange={e=>setForm({...form,condition:e.target.value as any})}>{['EXCELLENT','GOOD','FAIR','POOR'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Purchase date"><input className="input" type="date" value={form.purchaseDate||''} onChange={e=>setForm({...form,purchaseDate:e.target.value})}/></Field><Field label="Purchase cost"><input className="input" type="number" value={form.purchaseCost||0} onChange={e=>setForm({...form,purchaseCost:Number(e.target.value)})}/></Field><Field label="Warranty expiry"><input className="input" type="date" value={form.warrantyExpiry||''} onChange={e=>setForm({...form,warrantyExpiry:e.target.value})}/></Field><div/><div className="sm:col-span-2"><Field label="Lifecycle notes"><textarea className="input min-h-24" value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div><div className="sm:col-span-2 flex justify-end gap-2 border-t pt-4"><Button variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit">{editing?'Save changes':'Register asset'}</Button></div></form></Modal>
 <Modal open={Boolean(detail)} onClose={()=>setDetail(null)} title="Asset profile" size="lg">{detail&&<div className="space-y-5"><div className="rounded-[22px] bg-slate-950 p-5 text-white"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-300">{detail.assetCode}</p><h3 className="mt-2 text-2xl font-bold">{detail.name}</h3><p className="mt-1 text-sm text-slate-400">{detail.serialNumber}</p></div><div className="rounded-2xl bg-white/10 p-3"><HardDrive className="h-6 w-6"/></div></div></div><div className="grid gap-3 sm:grid-cols-2">{[['Category',ASSET_CATEGORY_LABELS[detail.category]],['Status',ASSET_STATUS_LABELS[detail.status]],['Department',detail.department],['Location',detail.location],['Vendor',detail.vendor],['Condition',detail.condition],['Purchase cost',formatCurrency(detail.purchaseCost)],['Warranty',formatDate(detail.warrantyExpiry)]].map(([k,v])=><div key={k} className="rounded-2xl border border-slate-200 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{k}</p><p className="mt-1 text-sm font-bold text-slate-900">{v||'—'}</p></div>)}</div><div className="rounded-2xl bg-slate-50 p-4 text-sm leading-6 text-slate-600">{detail.notes||'No additional lifecycle notes.'}</div></div>}</Modal>
 </div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="label">{label}</span>{children}</label>}
